### ISSUE TITLE
Steam information not loading?

### ISSUE THREAD

**Issue by masonticehurst** [Svenskunganka/OpenLoad#1]
Hey, I tried adding the soil themed loading screen to my server, for some reason when I join I do not see any of the information and it sticks on loading... (I have also set it up for database connection but that didn't work either.)

I've added the debugging lines into the ajax.php file but checked console and found no errors. I also have no idea where I can enable the fopen so any help would be appreciated.
Thanks.

**Comment by Svenskunganka** [comment]
Do you have a shared hosting plan?
Try adding `ini_set("allow_url_fopen", "true");` to ajax.php on the first line.

**Comment by masonticehurst** [comment]
Unfortunately I don't think this worked :/

**Comment by Svenskunganka** [comment]
If you run make a file called info.php an only put

```
<?php
php_info();
?>
```

in there, look for something about allow_url_fopen in there and tell me what the parameter says.

**Comment by masonticehurst** [comment]
Seems to be on:
http://i.gyazo.com/29009d9ea8371233dafc12bcc5d78870.png

**Comment by Svenskunganka** [comment]
Interesting. Have you made sure your Steam API key is working as it should?

**Comment by Mates** [comment]
Was this eventually solved? I'm having the exact same problem, Steam information is stuck on Loading...
I have allow_url_fopen enabled. In console, there was first this error:
    [blocked] The page at '<mydomain>/openload/index.php?template=soil&sid=1' was loaded over HTTPS, but ran insecure content from 'http://fonts.googleapis.com/css?family=Montserrat:400,700': this content should also be loaded over HTTPS.
I solved that by changing http to https in soil.css. Now there are no errors, but the Steam information still doesn't get loaded. I checked that my Steam API key is working fine.

**Comment by Svenskunganka** [comment]
Steam info is loading just fine for me. Check your PHP's error.log file and see if you find any errors there.

**Comment by Mates** [comment]
I guess there was something wrong on my side. I ended up rewriting the code a bit to suit my needs better and now it works. Oh well.
