### ISSUE TITLE
Errors.

### ISSUE THREAD

**Issue by bmxatvman14** [Svenskunganka/OpenLoad#2]
I'm getting these issues when I load. Nothing the loading screen is happening, None of the steam info is coming, none of the pointshop info, not even the players nor address.

Any help would be appreciated. 

  thrown in /home/rubergam/public_html/BMXLoad/v2/src/lib/SourceQuery/Socket.class.php on line 51
[18-Aug-2014 00:52:20 America/Chicago] PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not create socket: Failed to parse address ""' in /home/rubergam/public_html/BMXLoad/v2/src/lib/SourceQuery/Socket.class.php:51
Stack trace:
#0 /home/rubergam/public_html/BMXLoad/v2/src/lib/SourceQuery/SourceQuery.class.php(139): SourceQuerySocket->Open(NULL, 0, 3, 1)
#1 /home/rubergam/public_html/BMXLoad/v2/src/core/ajax.php(29): SourceQuery->Connect(NULL, NULL)
#2 {main}

  thrown in /home/rubergam/public_html/BMXLoad/v2/src/lib/SourceQuery/Socket.class.php on line 51
[18-Aug-2014 00:55:35 America/Chicago] PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not create socket: Failed to parse address ""' in /home/rubergam/public_html/BMXLoad/v2/src/lib/SourceQuery/Socket.class.php:51
Stack trace:
#0 /home/rubergam/public_html/BMXLoad/v2/src/lib/SourceQuery/SourceQuery.class.php(139): SourceQuerySocket->Open(NULL, 0, 3, 1)
#1 /home/rubergam/public_html/BMXLoad/v2/src/core/ajax.php(29): SourceQuery->Connect(NULL, NULL)
#2 {main}

  thrown in /home/rubergam/public_html/BMXLoad/v2/src/lib/SourceQuery/Socket.class.php on line 51

**Comment by bmxatvman14** [comment]
My understanding is that this is with allow_url_fopen... 

I have this turned off due to a security risk. May be better to find another way around this, but I can open it.

http://phpsec.org/projects/phpsecinfo/tests/allow_url_fopen.html

**Comment by Svenskunganka** [comment]
Please re-enabled `allow_url_fopen` again. It is crucial for OpenLoad to function.

There's no security breaches within OpenLoad, so it's safe to enable.
