### ISSUE TITLE
It's just "Loading" data, and no steamId is coming up

### ISSUE THREAD

**Issue by Xdeposh** [Svenskunganka/OpenLoad#4]
I've been trying to figure this out now for about 6 hours but it still wont work. I have allow_fopen_url. When I connect to my server I get this error in my Gmod console "[HTML] <br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><font face='Arial' size='1' color='#000000'><b>PHP Error Message</b></font></td></tr></table><br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Could not create socket: ' in /home/a4418322/public_html/openload/src/lib/SourceQuery/Socket.class.php:51
Stack trace:
#0 /home/a4418322/public_html/openload/src/lib/SourceQuery/SourceQuery.class.php(139): SourceQuerySocket-&gt;Open('88.89.146.211', 27005, 3, 1)
#1 /home/a4418322/public_html/openload/src/core/ajax.php(29): SourceQuery-&gt;Connect('88.89.146.211', 27005)
#2 {main}

  thrown in <b>/home/a4418322/public_html/openload/src/lib/SourceQuery/Socket.class.php</b> on line <b>51</b><br />
<br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><div align='center'><a href='http://www.000webhost.com/'><font face='Arial' size='1' color='#000000'>Free Web Hosting</font></a></div></td></tr></table>
[HTML] Uncaught SyntaxError: Unexpected token <"
And one more thing, in the src/config/config file, the servers there are supposed to be my public IP to the gmod server right?

**Comment by Svenskunganka** [comment]
You are using 000webhost.com, as far as I know you cannot make TCP connections from that host. You should purchase a hosting package or go with a better free host like x10hosting.com.

Either way the error says that OpenLoad cannot open a connection to your server (88.89.146.211:27005) so make sure your server is running and that's the correct IP. I just tried pinging your server and it seems to be down.

**Comment by Xdeposh** [comment]
Thank you so much :D I created a new hosting website at AlterVista and got it to work, but I got only one more problem now. It wont fetch the IP and I got this strange error "{"steamid":"STEAM_0:0:48273381","players":1,"playername":"","avatar":"","mapimage":"https:\/\/raw.githubusercontent.com\/Svenskunganka\/OpenLoad\/master\/templates\/strapquery\/img\/unknown_map.jpg","ip":"88.89.146.211:27015"}
"
By the way, thanks for fast response and I love your loadingurl design! :D Keep up the good work!

**Comment by Svenskunganka** [comment]
You have to bind your Steam API Key to your new website, as it's still bound to your previous website at 000webhost.com.

**Comment by Xdeposh** [comment]
But I have put my steam api In the config. Do I have to make a new one? ?

**Comment by Svenskunganka** [comment]
Yeah, as the steam api is bound to the domain you're using it on.

**Comment by Xdeposh** [comment]
Thanks :). How did you learn all this? You're a genius!

**Comment by Xdeposh** [comment]
Hmmmm, I did change the Steam API access code but I still get the error.
This is the loading URL "
gmodloadingurl.altervista.org/Openload/index.php?template=soil&sid=1 "

2014-10-08 12:26 GMT+02:00 Tom notifications@github.com:

**Comment by Svenskunganka** [comment]
Not sure what error you are getting, but it works perfectly fine for me. This is the JSON response I'm getting when using my CommunityID:

```
{
  "steamid":"STEAM_0:0:14114233",
  "players":1,
  "playername":"Svenskunganka",
  "avatar":"http:\/\/media.steampowered.com\/steamcommunity\/public\/images\/avatars\/e8\/e82256b15b9b6bec77ba3e45afc599085ffd6ba8_full.jpg",
  "mapimage":"https:\/\/raw.githubusercontent.com\/Svenskunganka\/OpenLoad\/master\/templates\/strapquery\/img\/unknown_map.jpg",
  "ip":"88.89.146.211:27015"
} 
```

Everything seems to work perfectly fine according to the response.

**Comment by Xdeposh** [comment]
hmmm :D Thanks for the response, It might not work for me because I'm
connecting to my server via that IP :D Thanks for the help and I'll now set
this as closed, so you don't have to be annoyed with more of my dumb
questions and issues :D Thanks for the help! You're the best!

2014-10-08 22:25 GMT+02:00 Tom notifications@github.com:
