### ISSUE TITLE
cant find the php.ini

### ISSUE THREAD

**Issue by 2spoonfulls** [Svenskunganka/OpenLoad#8]
where the hell is it located

**Comment by Svenskunganka** [comment]
Depends on what operating system your web server runs on, and where you installed PHP. Do you use a shared webhost, as in you pay monthly for a website from some company? If you do, you either have to open a support ticket with them or you should be able to edit the `php.ini` config directly from your control panel. If you have installed PHP on a server that you have direct access to (SSH for Linux or RDP for Windows), you can create a simple PHP script and run it to find out, as explained in this article: https://www.ostraining.com/blog/coding/phpini-file/

**Comment by glerinsonum** [comment]
@2spoonfulls @Svenskunganka Hi. 
Is there any website that tells. 

Get all links of this category film movies ACTION and puts to remote upload openload.co ?

**Comment by glerinsonum** [comment]
I would one plugin for chrome exention or firefox. 
That is OpenLoadLink Detector VID.

**Comment by Svenskunganka** [comment]
@glerinsonum I think you are in the wrong repository. This repository is not related to openload.co in any way.
